In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
# training Data features (Hours(sleep), Hours(study))
X = np.array([[3,5],[5,1],[7,2]])
# training Outputs (scores on test)
y = np.array([[73],[82],[91]])

In [3]:
X

array([[3, 5],
       [5, 1],
       [7, 2]])

In [4]:
y

array([[73],
       [82],
       [91]])

In [5]:
# Normalize the values or scale the values(feature scalling) 
# X = X/max(X), y = y/max(y)

column_wise_max_X_values = np.max(X,axis=0)
print(column_wise_max_X_values)
X = X/column_wise_max_X_values

# highest score is 100
y = y/100

[7 5]


In [6]:
X

array([[0.42857143, 1.        ],
       [0.71428571, 0.2       ],
       [1.        , 0.4       ]])

In [7]:
y

array([[0.73],
       [0.82],
       [0.91]])